[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "SyncTwin Parts Dropper"
description="Fills your material containers with parts"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "manufacturing"

# Keywords for the extension
keywords = ["kit", "manufacturing", "SyncTwin"]

# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/logo.png" 

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import ai.synctwin.parts_dropper_lite".
[[python.module]]
name = "ai.synctwin.parts_dropper_lite"
